### PR TITLE
feat: introduced a new variable for using the fury-kubernetes-karrier module

### PR DESCRIPTION
**Pull request by lzecca78**
Hi folks 👋 ,
after the creation of the https://github.com/sighupio/fury-kubernetes-karrier, we need to inject to this script the version of the module we want to use (right now a commit sha, tomorrow a git tag).
This PR introduce this feature 🚀

### CODE REVIEW

**Review by ralgozino — COMMENTED** [review]
Hi @lzecca78 
Have you considered Instead of `kubectl apply`ing directly the repo to install it as a regular module?
Is the change in the indentation required by the linter?

**Comment by lzecca78** [comment]
@ralgozino , the indentation is the same indentation that we follow in the other projects, that avoid linting issues, so Intellij applies it automatically,
regarding the change I did, is the very first change useful for this. Once we will have a module tagged (currently it is not because we need to tag also all the microservices), probably we will move the standard setup with a Furyfile, definitely

**Review by ralgozino — APPROVED** [review]
clear, thanks! 
I'd ask you to write a comment regarding the module vs direct apply in the script just to track it.

**Review by ralgozino — APPROVED** [review]

**Review by omissis — APPROVED** [review]
SBAM. perhaps we can rename `furyplatform-furyctl-runner` to `karrier-furyctl-runner`? @lzecca78 @ralgozino

**Comment by ralgozino** [comment]
> SBAM. perhaps we can rename `furyplatform-furyctl-runner` to `karrier-furyctl-runner`? @lzecca78 @ralgozino

lgtm

**Pull request merged**
