### PR TITLE
Use the default kind storage class instead of creating a new one

### PR DESCRIPTION
**Pull request by angelbarrera92**
Hii team.

~~With this PR i tried to mark all default storage class created by kind as non-default storage class as we deploy a default new one ;)~~

I think it should be a good practice about having only one default storage class, the default created by kind

Thanks!

### CODE REVIEW

**Comment by phisco** [comment]
I've been following this issue for a while, the implemented solution in the end was one of the workarounds suggested there (https://github.com/kubernetes-sigs/kind/issues/118)

**Comment by phisco** [comment]
We should try not deploying the new storage class and see if the problems I met have been solved. I was having troubles with the fury-kubernetes-logging's elasticsearch deployment at the time.

**Comment by angelbarrera92** [comment]
Ok, let me test it without deploying our storage class ;)

**Comment by angelbarrera92** [comment]
Now i removed the storage class created by us leaving the one created by kind ;)

**Pull request merged**
