### PR TITLE
Upgrade katalog container image with kustomize version 3

### PR DESCRIPTION
**Pull request by angelbarrera92**
Hi team.

As part of our journey to upgrade kustomize from 1 -> 3 i found an image (that i use in other pipeline) with an old kustomize version. This is caused my some problems in some pipelines.

Let's try to update the image we found.

Thanks!

### CODE REVIEW

**Comment by angelbarrera92** [comment]
As i understand, the old image tag is not going to be removed. A new image will be available and we should start using it.

**Comment by phisco** [comment]
Yes, pipelines explicitly refer to a version, which allows us to rollout gradually new versions, but also makes it a pain to propagate all the upgrades to all pipelines. We should think if this is really the best option.

**Comment by phisco** [comment]
LGTM

**Comment by angelbarrera92** [comment]
> Yes, pipelines explicitly refer to a version, which allows us to rollout gradually new versions, but also makes it a pain to propagate all the upgrades to all pipelines. We should think if this is really the best option.

I agree.

Maybe some image tags like: stable, dev... also latest... i don't know. Some times is better to use an explicit version instead of one dynamic version.

**Comment by phisco** [comment]
I think we could start an issue about the tagging convention discussion.

**Comment by angelbarrera92** [comment]
[Write product development / release process](https://trello.com/c/tKEywItE/440-write-product-development-release-process)

**Comment by angelbarrera92** [comment]
> I think we could start an issue about the tagging convention discussion.
>  [Write product development / release process](https://trello.com/c/tKEywItE/440-write-product-development-release-process)

Done!

**Pull request merged**
